spring:
  application:
    name: coding
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  security:
    user:
      password: admin
      name: admin
  h2:
    console:
      path: /h2-console
      enabled: 'true'
  jpa:
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  sql:
    init:
      mode: always
